services:
  server:
    build: ./src/PlannerServer
    container_name: api-server
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=PlannerDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
    ports:
      - "5000:80"

  client:
    build: ./src/PlannerClient
    container_name: blazor-client
    depends_on:
      - server
    ports:
      - "5001:80"