services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - planner-net

  plannerclient:
    build:
      context: .
      dockerfile: src/PlannerClient/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - planner-net

  plannerserver:
    build:
      context: .
      dockerfile: src/PlannerServer/Dockerfile
    ports:
      - "5000:80"
    networks:
      - planner-net

volumes:
  mssql-data:

networks:
  planner-net:
    driver: bridge
