name: .NET + Docker Compose CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o ./output

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./output

  test_containers:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
  
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app
        path: ./app

    - name: Set up Docker Compose
      run: |
        docker compose version || docker-compose version

    - name: Build and Start Services
      run: |
        docker compose up -d --build

    - name: Run health checks or integration tests (optional)
      run: |
        docker ps

    - name: Shut down services
      if: always()
      run: docker compose down
