name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        docker compose version || docker-compose version

    - name: Build and Start Services
      run: |
        docker compose up -d --build

    - name: Run health checks or integration tests (optional)
      run: |
        docker ps
        # Add test commands here, e.g., curl localhost:yourport or docker exec your-container

    - name: Shut down services
      if: always()
      run: docker compose down
